version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/movie_finder
hooks:
  BeforeInstall:
    - location: scripts/deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy/after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/deploy/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/deploy/validate_service.sh
      timeout: 180
      runas: root
