# Generated by Django 5.2.7 on 2025-11-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('movie', '0011_alter_recommendedmovie_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                (
                    'collection',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='collection_movies',
                        to='collection.collection',
                    ),
                ),
                (
                    'movie',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='movie_collections',
                        to='movie.movie',
                    ),
                ),
            ],
            options={
                'ordering': ['position', 'added_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(related_name='collections', through='collection.CollectionMovie', to='movie.movie'),
        ),
        migrations.AddConstraint(
            model_name='collectionmovie',
            constraint=models.UniqueConstraint(fields=('collection', 'movie'), name='collection_movie_unique'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='collection_owner_name_unique'),
        ),
    ]
