# Generated by Django 5.2.7 on 2025-12-08 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0002_collections_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='collection_owner_name_unique',
        ),
    ]
