# Generated by Django 5.2.7 on 2025-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0003_remove_collection_collection_owner_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='design',
            field=models.CharField(default='', max_length=255, blank=True),
        ),
    ]
