# Generated by Django 4.0.7 on 2022-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_likemovie_like-user-movie-unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlatermovie',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='watchlater-user-movie-unique'),
        ),
    ]
