# Generated by Django 5.0.7 on 2024-07-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
