# Generated by Django 3.2.9 on 2021-12-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_favoritemovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovie',
            name='user',
            field=models.CharField(default='Dadaya', max_length=69),
        ),
    ]
