# Generated by Django 3.2.9 on 2021-12-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_auto_20211206_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovieuser',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
