# Generated by Django 3.2.9 on 2021-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_alter_favoritemovieuser_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovieuser',
            name='year',
            field=models.CharField(max_length=16),
        ),
    ]
