# Generated by Django 4.0.6 on 2022-07-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_auto_20220113_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
