# Titles and design for curated collections. Design values match frontend (CreateCollectionModal):
# action, brain, comedy, drama, fantasy, horror, lupa, mystery, romance, scifi.
# Run build_curated_collections_seed once to fetch from OMDb and write curated_collections_seed.json.

COLLECTIONS = [
    (
        'New Year',
        'Holiday and New Year movies',
        'action',
        [
            'Home Alone',
            'Home Alone 2: Lost in New York',
            'Love Actually',
            'Die Hard',
            'The Holiday',
            'A Christmas Carol',
            'The Polar Express',
            'Klaus',
            'Last Christmas',
            'Bad Santa',
        ],
    ),
    (
        'Horror',
        'Horror and thrillers',
        'horror',
        [
            'Hereditary',
            'It',
            'Insidious',
            'The Conjuring',
            'The Babadook',
            'The Lighthouse',
            'The Shining',
            'Saw',
            'Paranormal Activity',
            'A Quiet Place',
        ],
    ),
    (
        'Comedy',
        'Comedy movies',
        'comedy',
        [
            'The Intouchables',
            'The Mask',
            'Bruce Almighty',
            'The Hangover',
            "Don't Look Up",
            'The Dictator',
            'Superbad',
            "We're the Millers",
            'Catch Me If You Can',
            'Zombieland',
        ],
    ),
    (
        'Drama',
        'Drama films',
        'drama',
        [
            'The Shawshank Redemption',
            'Forrest Gump',
            'The Green Mile',
            'Fight Club',
            'Requiem for a Dream',
            "Schindler's List",
            'Joker',
            'Gladiator',
            'American Beauty',
            'Life Is Beautiful',
        ],
    ),
    (
        'Action',
        'Action and adventure',
        'action',
        [
            'John Wick',
            'The Dark Knight',
            'Mission: Impossible',
            'The Matrix',
            'Terminator 2: Judgment Day',
            'Mad Max: Fury Road',
            'The Raid',
            'Inception',
            'Die Hard',
            'The Transporter',
        ],
    ),
    (
        'Romance',
        'Romantic films',
        'romance',
        [
            'Titanic',
            'The Notebook',
            'Pride & Prejudice',
            'La La Land',
            'Me Before You',
            'Love and Other Drugs',
            'Her',
            'Roman Holiday',
            'Before Sunrise',
            'Love Actually',
        ],
    ),
    (
        'Sci-Fi',
        'Science fiction and fantasy',
        'scifi',
        [
            'Interstellar',
            'Inception',
            'The Matrix',
            'Dune',
            'Avatar',
            'Blade Runner 2049',
            'Star Wars',
            'Back to the Future',
            'Arrival',
            'eXistenZ',
        ],
    ),
    (
        'Documentary',
        'Documentary films',
        'brain',
        [
            '13th',
            'The Social Dilemma',
            'Searching for Sugar Man',
            'Planet Earth',
            'Cosmos',
            'Inside Job',
            'Free Solo',
            'Icarus',
            'The Last Dance',
            'Our Planet',
        ],
    ),
    (
        'Anime',
        'Anime and animation',
        'fantasy',
        [
            'Spirited Away',
            'My Neighbor Totoro',
            'Your Name',
            'Princess Mononoke',
            'Akira',
            'Ghost in the Shell',
            "Howl's Moving Castle",
            'Weathering with You',
            'Grave of the Fireflies',
            'Perfect Blue',
        ],
    ),
    (
        'Classic',
        'Classic cinema',
        'drama',
        [
            'The Godfather',
            'Casablanca',
            '12 Angry Men',
            'Citizen Kane',
            'Roman Holiday',
            'City Lights',
            'Psycho',
            'Seven Samurai',
            'Gone with the Wind',
            'Some Like It Hot',
        ],
    ),
    (
        'Family',
        'Family-friendly movies',
        'fantasy',
        [
            'The Lion King',
            'Toy Story',
            'Up',
            'Shrek',
            'Frozen',
            'Ratatouille',
            'Paddington',
            'My Neighbor Totoro',
            'Finding Nemo',
            'Klaus',
        ],
    ),
    (
        'Top IMDb',
        'Top-rated on IMDb',
        'lupa',
        [
            'The Shawshank Redemption',
            'The Godfather',
            'The Dark Knight',
            'The Godfather Part II',
            '12 Angry Men',
            "Schindler's List",
            'The Lord of the Rings: The Return of the King',
            'Pulp Fiction',
            'The Good, the Bad and the Ugly',
            'Fight Club',
        ],
    ),
]
