# Generated by Django 5.0.7 on 2024-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
