# Generated by Django 5.0.7 on 2025-09-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0005_country_language_writer_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='movie_ratings',
                to='movie.movie',
            ),
        ),
    ]
