# Generated by Django 5.0.7 on 2025-09-14 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0006_alter_rating_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='released',
            new_name='released_date',
        ),
    ]
