# Generated by Django 5.2.6 on 2025-09-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0008_alter_movie_awards_alter_movie_imdb_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_date', models.DateField()),
                ('position', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_entries', to='movie.movie')),
                (
                    'user',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_movies', to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('user', 'recommendation_date', 'movie'), name='recommended-user-movie-unique')],
            },
        ),
    ]
