# Generated by Django 5.2.6 on 2025-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0009_recommendedmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedmovie',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendedmovie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
