# Generated by Django 5.2.6 on 2025-09-28 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0010_recommendedmovie_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedmovie',
            options={},
        ),
        migrations.RemoveField(
            model_name='recommendedmovie',
            name='position',
        ),
    ]
