# Generated by Django 3.2.9 on 2021-12-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=128)),
                ('imdb_id', models.CharField(max_length=128)),
                ('wiki_link', models.CharField(max_length=255)),
            ],
        ),
    ]
